<a href="https://colab.research.google.com/github/jaishrm07/pytorch-end-to-end/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cpu


## Introduction to Tensors

### creating tensors

PyTorch tensors are created using "torch.Tensor()" = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6051, 0.0837, 0.9356, 0.4547],
        [0.9293, 0.1990, 0.4025, 0.5296],
        [0.5458, 0.4796, 0.3568, 0.9290]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

`torch.arange()` = https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten.shape)
one_to_ten.ndim

torch.Size([10])


1

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes are one of the 3 big erros you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

**Precision in Computing**:
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (eg. float32 or int64 )
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting Information (Attributes) from tensors:

1. Tensors not right datatype -- to get datatype from tensor, can use `tensor.dtype`
2. Tensors not right shape -- to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device -- to get device from tensor, can use `tensor.device`

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix Multiplications

Two Mains ways of performing multiplication in NN and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

more information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two mains rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (2, 6)` will work
* `(3, 2) @ (6, 2)` will not work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(3, 2) @ (2, 6)` --> `(3,6)` from above

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
# Matrix multiplication
print(tensor, "*", tensor)
torch.matmul(tensor, tensor)

tensor([10, 20, 30]) * tensor([10, 20, 30])


tensor(1400)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 976 µs, sys: 84 µs, total: 1.06 ms
Wall time: 886 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

# Uses Vectorization to make the computing faster
# always use torch.operations for doing calculation

CPU times: user 84 µs, sys: 98 µs, total: 182 µs
Wall time: 169 µs


tensor(1400)

### One of the most common errors in deep learning: Shape Errors

In [ ]:
# Shapes for
# torch.mm() and torch.matmul(), both are same.

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_A = torch.rand(3, 4)
tensor_A.shape

torch.Size([3, 4])

In [ ]:
tensor_A1 = tensor_A.T # .T transposes the matrix
tensor_A1.shape

torch.Size([4, 3])

## Finding the min, max, mean, sum, etc (tensor aggragation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x. max()

(tensor(1), tensor(91))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

We want where maximum or minimum value appears.

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# FInd the position in tensor that has minimum value with argmin() --> return index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## (MANIPULATING TENSORS)Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the orignal tensor.
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack). https://pytorch.org/docs/stable/generated/torch.stack.html
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way. https://pytorch.org/docs/stable/generated/torch.permute.html

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed.shape)
print(x_unsqueezed)

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
torch.Size([9, 1])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# x_permuted and x_orignal both shares the same memory. permuted() does not create a new tensor in memory.

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_permuted[:2, :3, :3]

tensor([[[0.1618, 0.0101, 0.6164],
         [0.7656, 0.1764, 0.8956],
         [0.7787, 0.6113, 0.1859]],

        [[0.0304, 0.6436, 0.3272],
         [0.1970, 0.7121, 0.8332],
         [0.4371, 0.2213, 0.3727]]])

In [ ]:
x_permuted

tensor([[[0.1618, 0.0101, 0.6164,  ..., 0.5414, 0.3790, 0.0635],
         [0.7656, 0.1764, 0.8956,  ..., 0.4586, 0.3513, 0.9532],
         [0.7787, 0.6113, 0.1859,  ..., 0.5888, 0.7398, 0.3635],
         ...,
         [0.6281, 0.4570, 0.7632,  ..., 0.1133, 0.6548, 0.5002],
         [0.2050, 0.8876, 0.9583,  ..., 0.2684, 0.2480, 0.3708],
         [0.5275, 0.7402, 0.3682,  ..., 0.2317, 0.5688, 0.9083]],

        [[0.0304, 0.6436, 0.3272,  ..., 0.5607, 0.8720, 0.4765],
         [0.1970, 0.7121, 0.8332,  ..., 0.4129, 0.0045, 0.1897],
         [0.4371, 0.2213, 0.3727,  ..., 0.4837, 0.1352, 0.2675],
         ...,
         [0.5290, 0.7967, 0.3051,  ..., 0.2993, 0.8637, 0.7684],
         [0.0669, 0.5297, 0.5404,  ..., 0.7951, 0.4182, 0.3689],
         [0.6777, 0.8937, 0.6992,  ..., 0.5631, 0.4738, 0.3572]],

        [[0.9860, 0.4864, 0.3253,  ..., 0.4931, 0.9371, 0.2555],
         [0.3620, 0.1406, 0.0846,  ..., 0.9277, 0.2179, 0.4498],
         [0.1993, 0.1604, 0.7186,  ..., 0.4362, 0.1040, 0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[0, :, 0].ndim

1

In [ ]:
x[0, 1, :]

tensor([4, 5, 6])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy --> PyTorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

# defaulty

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**default datatype of NumPy is float64 and Pytorch is float32**

## Reproducibility (trying to take random out of random)

In short how a NN learns:

`start with random numbers -> tensor operations -> update randome numbers to try and make them better representations of the data -> again -> again -> again`

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

https://pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed

In [ ]:
import torch

# creatr two randome tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3156, 0.4924, 0.1596, 0.6131],
        [0.0801, 0.4840, 0.5954, 0.8322],
        [0.5683, 0.5425, 0.4197, 0.5447]])
tensor([[0.7723, 0.8879, 0.3306, 0.0522],
        [0.8639, 0.1098, 0.8233, 0.1814],
        [0.4494, 0.4984, 0.2205, 0.0092]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Rnning tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

### 1. Getting a GPU

1. Easiest -- get a google collab pro
2. purchase GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this
https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html


Eg run on GPU if available.

In [ ]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# create a tensor (default on the cpu)

tensor = torch.tensor([1, 2, 3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
### 4. Moving tensors back to the CPU
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# to fix the GPU tensor with NumPy issue, we can fist set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

# multiple GPU for distributing computing

## Exercises & Extra-curriculum

